#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Oct 13, 2021 05:17:06 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m62" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 690x502+277+65
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 336 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 530 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.fra45
    checkbutton $top.che48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text SP -variable checkSP 
    vTcl:DefineAlias "$top.che48" "CheckbuttonSP" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.che48
    checkbutton $top.che49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text PV -variable checkPV 
    vTcl:DefineAlias "$top.che49" "CheckbuttonPV" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.che49
    checkbutton $top.che50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text ERR -variable checkERR 
    vTcl:DefineAlias "$top.che50" "CheckbuttonERR" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.che50
    checkbutton $top.che51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text CP -variable checkCP 
    vTcl:DefineAlias "$top.che51" "CheckbuttonCP" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.che51
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -borderwidth 9 -compound center -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Visualización 
    vTcl:DefineAlias "$top.lab60" "Label_visualizacion" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab60
    menu $top.m62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    text $top.tex47 \
        -background #000000 -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground blue \
        -selectforeground white -width 45 -wrap word 
    $top.tex47 configure -font "TkTextFont"
    $top.tex47 insert end text
    vTcl:DefineAlias "$top.tex47" "Text1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tex47
    text $top.tex48 \
        -background #0000ff -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground blue \
        -selectforeground white -width 45 -wrap word 
    $top.tex48 configure -font "TkTextFont"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "Text1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tex48
    text $top.tex49 \
        -background #ff0000 -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground blue \
        -selectforeground white -width 45 -wrap word 
    $top.tex49 configure -font "TkTextFont"
    $top.tex49 insert end text
    vTcl:DefineAlias "$top.tex49" "Text1_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tex49
    text $top.tex50 \
        -background #00e800 -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground blue \
        -selectforeground white -width 45 -wrap word 
    $top.tex50 configure -font "TkTextFont"
    $top.tex50 insert end text
    vTcl:DefineAlias "$top.tex50" "Text1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tex50
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #939393 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab52
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Selección planta} 
    vTcl:DefineAlias "$top.lab55" "Label_sel_planta" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab55
    ttk::combobox $top.tCo59 \
        -values {Planta 1, Planta 2, Planta 3, Planta 4, Planta 5} \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo59" "Sel_planta" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tCo59
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #939393 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.lab45" "Labe2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab45
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command BOTON_ON_OFF \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text ON/OFF 
    vTcl:DefineAlias "$top.but46" "ButtonON_OFF" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but46
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Control marcha/paro} 
    vTcl:DefineAlias "$top.lab47" "Label_marcha_paro" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab47
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #939393 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.lab48" "Label3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab48
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Selección setpoint} 
    vTcl:DefineAlias "$top.lab53" "Label_set_point" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab53
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command BOTON_ACTUALIZAR \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text ACTUALIZAR 
    vTcl:DefineAlias "$top.but54" "ButtonActualizar" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but54
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #939393 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Set Point} 
    vTcl:DefineAlias "$top.lab56" "Label_sp" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab56
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 54 
    vTcl:DefineAlias "$top.ent57" "EntrySP" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent57
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.02 -width 0 -relwidth 0.768 \
        -height 0 -relheight 0.699 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.86 -y 0 -rely 0.178 -width 0 -relwidth 0.104 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 0 -relx 0.86 -y 0 -rely 0.289 -width 0 -relwidth 0.109 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 0 -relx 0.875 -y 0 -rely 0.4 -width 0 -relwidth 0.089 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.che51 \
        -in $top -x 0 -relx 0.875 -y 0 -rely 0.511 -width 0 -relwidth 0.081 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.797 -y 0 -rely 0.04 -width 0 -relwidth 0.187 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tex47 \
        -in $top -x 0 -relx 0.814 -y 0 -rely 0.2 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.009 -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 0 -relx 0.814 -y 0 -rely 0.311 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.009 -anchor nw -bordermode ignore 
    place $top.tex49 \
        -in $top -x 0 -relx 0.814 -y 0 -rely 0.422 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.009 -anchor nw -bordermode ignore 
    place $top.tex50 \
        -in $top -x 0 -relx 0.814 -y 0 -rely 0.533 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.009 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.725 -y 0 -rely 0.737 -width 0 -relwidth 0.265 \
        -height 0 -relheight 0.251 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.739 -y 0 -rely 0.757 -width 0 -relwidth 0.238 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tCo59 \
        -in $top -x 0 -relx 0.754 -y 0 -rely 0.857 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.362 -y 0 -rely 0.737 -width 0 -relwidth 0.28 \
        -height 0 -relheight 0.251 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.42 -y 0 -rely 0.837 -width 107 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.377 -y 0 -rely 0.757 -width 0 -relwidth 0.252 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.737 -width 0 -relwidth 0.265 \
        -height 0 -relheight 0.251 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.757 -width 0 -relwidth 0.238 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.072 -y 0 -rely 0.916 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.837 -width 0 -relwidth 0.136 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.159 -y 0 -rely 0.837 -width 54 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

